# Copyright (c) 2020 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
org = "ballerinax"
name = "choreo"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../choreo-extension-native/build/libs/choreo-extension-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "choreo-extension-native"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/jaeger-core-@jaeger.version@.jar"
groupId = "io.jaegertracing"
artifactId = "jaeger-core"
version = "@jaeger.version@"

[[platform.java11.dependency]]
path = "./lib/opentracing-noop-@opentracing.version@.jar"
groupId = "io.opentracing"
artifactId = "opentracing-noop"
version = "@opentracing.version@"

[[platform.java11.dependency]]
path = "./lib/grpc-protobuf-@grpc.version@.jar"
groupId = "io.grpc"
artifactId = "grpc-protobuf"
version = "@grpc.version@"

[[platform.java11.dependency]]
path = "./lib/grpc-stub-@grpc.version@.jar"
groupId = "io.grpc"
artifactId = "grpc-stub"
version = "@grpc.version@"

[[platform.java11.dependency]]
path = "./lib/grpc-netty-shaded-@grpc.version@.jar"
groupId = "io.grpc"
artifactId = "grpc-netty-shaded"
version = "@grpc.version@"

[[platform.java11.dependency]]
path = "./lib/grpc-api-@grpc.version@.jar"
groupId = "io.grpc"
artifactId = "grpc-api"
version = "@grpc.version@"

[[platform.java11.dependency]]
path = "./lib/grpc-core-@grpc.version@.jar"
groupId = "io.grpc"
artifactId = "grpc-core"
version = "@grpc.version@"

[[platform.java11.dependency]]
path = "./lib/grpc-protobuf-lite-@grpc.version@.jar"
groupId = "io.grpc"
artifactId = "grpc-protobuf-lite"
version = "@grpc.version@"

[[platform.java11.dependency]]
path = "./lib/grpc-context-@grpc.version@.jar"
groupId = "io.grpc"
artifactId = "grpc-context"
version = "@grpc.version@"

[[platform.java11.dependency]]
path = "./lib/guava-@guava.version@.jar"
groupId = "com.google.guava"
artifactId = "guava"
version = "@guava.version@"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-@protobuf.version@.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "@protobuf.version@"

[[platform.java11.dependency]]
path = "./lib/perfmark-api-@perfmark.version@.jar"
groupId = "io.perfmark"
artifactId = "perfmark-api"
version = "@perfmark.version@"
